.github/verible.waiver
.github/workflows/gitlab-ci.yml
.github/workflows/lint.yml
.gitignore
.gitlab-ci.yml
scripts/vsim_ret_error.sh
target/sim/vsim/start.chimera_soc.tcl

This PR implements a basic CI flow divided (for now) in 2 workflows (`.github/workflows`):
- a workflow for public actions, taking care of linting for license headers, SystemVerilog codestyle, and C codestyle
- a workflow triggering runners on our internal GitLab, for regression tests using proprietary tools
The jobs executed by our internal runners are described in `.gitlab-ci.yml`.
For now, the hardware is built using QuestaSim and a basic test is executed.
CI failure is currently expected both for linting and regression test.
Next steps:

Implement basic CI flow

---

.gitignore
.gitlab-ci.yml

This PR adds support to run multiple regression tests in parallel 
* Support to run more than one regression test in CI
* vsim now outputs one transcript per test
* Each transcript is stored as an artifact
* Artifacts are kept for up to 4 weeks

Add support for multiple parallel functional regression test

---

Bender.lock
Bender.yml

Update Bender.lock to reflect updated memory island dependency

---

.gitlab/gitlab-ci.yml
hw/chimera_cluster_adapter.sv
hw/chimera_top_wrapper.sv
hw/regs/chimera_reg_pkg.sv
hw/regs/chimera_reg_top.sv
hw/regs/chimera_regs.hjson
sw/include/regs/soc_ctrl.h
sw/tests/testMemBypass.c
target/sim/vsim/setup.chimera_soc.tcl

* Bypass register for wide axi port in cluster
* Sw test to check its behaviour

Bypass wide memory register

---

Bender.lock
Bender.yml
Makefile
chimera.mk
hw/chimera_pkg.sv
hw/chimera_top_wrapper.sv
hw/narrow_adapter.sv
requirements.txt
target/sim/src/fixture_chimera_soc.sv
target/sim/src/tb_chimera_soc.sv
target/sim/src/vip_chimera_soc.sv

Introduces support for 32 Bit host system (AXI Addrwidth & Datawidth) with Clusters using 32 Bit Addrwidth and 64 Bit Datawidth. 
* `narrow_adapter` to adapter between 32 Bit and 64 Bit Datawidth domains.
* Default Cfg now uses 32 Bit `AxiDataWidth` and 32 Bit `AddressWidth` Host
* Default Cfg now uses 64 Bit `DataWidth`  and 32 Bit `AddressWidth` Snitch Clusters. Adjustable via `chimera_pkg`
* Bumped `iDMA` commit which fixes incompatibility with mixed 64- and 32-Bit Datawidth systems
* Removed `slink`, `VGA`, `USB` ports from `chimera_top_wrapper`
* Removed `slink`-specific fixture functions

Add support for 32 AXI Data & Address width

---

Bender.lock
Bender.yml

This PR updates the Bender YAML file to align the **RISC-V debug module** with the [latest fixes](https://github.com/pulp-platform/riscv-dbg/commit/5b21f3504fc3913320b39b477ef2a4274e09581d) provided by @Scheremo.

Align RISCV Debug Module

---

Bender.lock
Bender.yml

After discussion here: https://github.com/pulp-platform/riscv-dbg/pull/171
We can revert the latest commit; the "proper" fix is to relax JTAG frequency.

Revert Commit #69cc1bc

---

Bender.lock
Bender.yml
hw/bootrom/snitch/snitch_startup.c
hw/chimera_clu_domain.sv
hw/chimera_cluster.sv
hw/chimera_cluster_adapter.sv
hw/chimera_pkg.sv
hw/chimera_top_wrapper.sv
sw/include/soc_addr_map.h
sw/lib/offload.c

Extracts the clusters from `chimera_top_wrapper` to `chimera_clu_domain` and `chimera_cluster`. 
Also reconfigures all adapters to minimize AXI ID widths.
* `chimera_clu_domain` which wraps cluster instantiation
* `chimera_cluster` which instantiates a single cluster and all necessary adapters
* Cluster's Narrow AXI ID width is now converted to width 1
* Wide AXI ID width is now converted to width 1
* Offload API now takes into account possibly varying numbers of cores per cluster

HW: Refactor Cluster integration

---

Bender.yml
hw/chimera_pkg.sv
hw/chimera_top_wrapper.sv
sw/include/regs/soc_ctrl.h
sw/include/soc_addr_map.h
sw/lib/offload.c
sw/tests/testMemBypass.c

This PR adds the required logic for the Chimera PD target.
- APB ports to access external registers: padframe configuration registers and FLL registers.
- A temporary mechanism to fix the race condition that occurs when the host offloads code before the clusters are ready (WFI).

ASIC Target

---

.gitignore
Makefile
chimera.mk
requirements.txt
sw/sw.mk
target/sim/sim.mk
utils/utils.mk

This PR is an attempt to improve the makefile flow of the project.
Makefrags of each project directory (`utils`, `sw`, `target/*`) are now located in that directory, and included from the main `chimera.mk` makefile (see https://github.com/pulp-platform/chimera/pull/28/files#diff-00aa5349c729bdf6161632c838730b4db54ca6a45d2276428467a47c553278f7R75-R79).
This gives maximum flexibility for the "interaction" of different makefrags, and also keeps things tidy as the root directory does not contain anymore many different unrelated makefrags.
Each directory's makefrag also has an include guard to prevent multiple inclusions.
Moreover, all targets can be called from the root directory.
Additionally, the padrick binary is now downloaded as part of `utils` through the makefile.
This is useful for …

Improve makefile flow

---

hw/chimera_pkg.sv
hw/chimera_top_wrapper.sv

As the title says, this PR clarifies the naming of external registers.

hw: Make external register mapping + naming more explicit

---

.gitlab/gitlab-ci.yml
Bender.lock
Bender.yml
sw/tests/testPeripheralsGating.c

This PR aligns Chimera with the latest Cheshire version supporting clock gating logic for the internal peripherals. 
Update Bender dependency to point to the correct Cheshire's revision
Add software testbench to use the clock gating logic inside Cheshire.

Add clock gate peripherals

---

hw/chimera_pkg.sv
hw/chimera_top_wrapper.sv

This PR aims to replace the multiple APB ports currently used for configuring the external PADs and FLLs configuration registers with a single shared port. This change eliminates the need to introduce additional ports for future physically aware extensions, such as adding more FLLs, PADs, or PMU controller registers.
All _reg_bus_ requests directed outside the Chimera_SoC are now included in the same address map rule. These requests are converted into the AMBA APB protocol and routed through a single APB interface.

APB interface

---

hw/chimera_clu_domain.sv
hw/chimera_cluster.sv

This PR modifies the cluster interface to use flattened AXI ports instead of the classic structured types defined in `axi/typedef.sv`.
The reason for this change is to address limitations introduced by the UPF standard, as supported by QuestaSim. Specifically, when isolation strategies are applied, UPF cannot handle ports with "complex" types, such as AXI ports, which are structured.
To resolve this issue, signals are flattened at the interface of each power domain and then internally reassigned to new structured signals, which can be propagated to downstream modules.
These types are defined for the flattened ports at the _chimera_cluster_ interface and must not be overwritten:
- narrow_in_resp_flat_t
- narrow_out_req_flat_t
- wide_out_req_flat_t  
These flattened ports have been …

UPF Cluster AXI Structured Ports 

---

Bender.lock
Bender.yml

This PR updates the cheshire dependency, which updates the CVA6 dependency, which now configures the address translation between virtual addresses and physical addresses to use the same VLEN and PLEN if there is no MMU instantiated.

CVA6 PLEN fix

---

hw/chimera_pkg.sv
hw/chimera_top_wrapper.sv
target/sim/src/fixture_chimera_soc.sv
target/sim/vsim/start.chimera_soc.tcl

This PR reintroduces the `SelectCfg` parameter to allow selection of the Chimera Configuration structure.
Additionally, the `start.chimera_soc.tcl` file has been modified to prevent `-GSelectCfg` from overwriting parameters with the same name in different modules.

Reintroduced SelectCfg parameter

---

.gitignore
hw/chimera_memisland_domain.sv

This PR add an `axi_cut` module inside the `memory_island_domain` to cut the combinatorial path between the memory island response and request channels when passing through the `axi_riscv_atomics_structs` module.

[HW]: Add axi cut in the memory island domain to remove timing loops

---

Bender.lock
Bender.yml

This PR revert the AXI version to `0.39.3` due to yanking of `0.39.4`.
Both Cheshire and the Memory Island pointed to the yanked version.
**Note:** This PR will be merged once the Pull Request on the [Memory Island](https://github.com/pulp-platform/memory_island/pull/13) repo will be accepted.

Bump Cheshire dependencies to revert AXI version

---

target/sim/src/vip_chimera_soc.sv

This PR introduces some few adjustment to the Testbench to improve the observability when printing a word with UART.
Additionally, it also modify some parameters due to some issues encountered when testing the Chimrea PD design.
the goal of this PR, is to end up with a shared version of the VIP module.
The reason why the `idle_cycles`  have been increased to 4000, is to work around an issue with the task [jtag_poll_bit0](https://github.com/pulp-platform/chimera/blob/314e9477c051b01471efe2f2ff7741303caea4e4/target/sim/src/vip_chimera_soc.sv#L213C18-L213C32). This task uses the Debug Module function [read_dmi_exp_backoff](https://github.com/pulp-platform/riscv-dbg/blob/618ee6e0e2610ef47e0dcc4df6748af3dffff731/tb/jtag_dmi/jtag_test.sv#L229), which should not be used for read operations with …

[TB]: Extend testbench to improve debugging

---

README.md
chimera.mk
target/sim/sim.mk

This PR should solve issue #9. 
It introduces two make targets to build and clean the entire Chimera SoC simplifying the make flow. 
By running `make chim-all` the SW and RTL are built while `make chim-clean` can be used to delete both the binaries and the RTL compilation script. 
In this way, the building flow shoudl be the follwoing:
- `bender checkout`
- `make chim-all`
Additionally, some simulation flags that were mistakenly removed in #43 have been reintroduced.

[MK]: Add make targets to build/clean the entire chimera SoC

---

hw/chimera_pkg.sv
target/sim/vsim/start.chimera_soc.tcl

This PR increases the bank size of the memory island from 1024 to 2048 words. Now the SoC has a 256 kiB memory island made of 32 narrow banks.

[RTL]: Increase Memory Island bank depth

---

Bender.yml
Makefile
requirements.txt
utils/utils.mk

The global makefile variables defined in a way like
```
CHS_ROOT    ?= $(shell $(BENDER) path cheshire)
SNITCH_ROOT ?= $(shell $(BENDER) path snitch_cluster)
```
call `bender checkout` any time whichever make command is executed, clogging stdout with uninformative output and slowing down operation. Thanks @ezelioli @creinwar ❤️ 
This PR solves mainly this issue and applies other small fixes.

Small QoL (quality-of-life) improvements

---

target/sim/sim.mk

The HyperBus model can no longer be automatically downloaded from the Invecas page because the [link](https://www.infineon.com/dgdl/Infineon-S27KL0641_S27KS0641_VERILOG-SimulationModels-v05_00-EN.zip?fileId=8ac78c8c7d0d8da4017d0f6349a14f68) now leads to a login page, preventing the automatic retrieval of the zip file containing the model.
To address this, the manually downloaded model has been placed on one of the IIS machines (simba). The Make flow used to build the testbench will now fetch the model directly from that machine, which resolves the CI issue.
This fix allows us to continue development using the CI, but we need a better long-term solution so that the repository can remain open-source and still be used from others.
**This PR is necessary to have a working nonfree CI and to …

[HOT FIX]: Hard code hyperbus model source from internal machine

---

Makefile

This PR introduces an helper target into the makefile to collect some documentations for the possible targets that can be run.
By running `make help` you'll get the list of targets with a short explanation of their usage.

Add help target into Makefile to include rough documentation

---

target/sim/src/vip_chimera_soc.sv

This PR adds UART debugging capabilities in the `vip_chimera_soc.sv` module by introducing a writeback mechanism and a FIFO for writeback handling in the testbench.
- **Added a new UART writeback mechanism**:
- Introduced a `UartWriteBack[5:0]` local parameter with the value `"UartWB"`.
- Implemented a comparison against `UartWriteBack` in the UART handling logic.
- When a match is detected, a predefined writeback message (`"WB OK"`) is sent via UART.
- **Added a FIFO buffer for UART writeback**:
- Introduced a static FIFO (`uart_fifo`) to store all received bytes.
- Enables the testbench to track UART transactions and trigger the writeback message.
- This change was made to **test the functionality of the UART peripheral** in Chimera after implementing its **driver and HAL** in the …

[Verification] UART Debugging and Writeback
